FROM node:21 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY .env.docker .env
COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
